@startuml
actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC2 as "Get salaries
    by department"

    usecase UCa as "Print salaries"

    HR - UC2
    UC2 ..> UCa : include
    UC2 - Database
}

@enduml
