@startuml
actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC7 as "Update an
    employee's details"

    usecase UCa as "Validate updated
    employee data"

    HR - UC7
    UC7 ..> UCa : include
    UC7 - Database
}

@enduml
