@startuml
actor HR as "HR Advisor"

rectangle Database

rectangle "HR System" {
    usecase UC6 as "Get employee details
    by employee number"

    usecase UCa as "Print employee
    details"

    HR - UC6
    UC6 ..> UCa : include
    UC6 - Database
}

@enduml
